### ISSUE TITLE
WPF Designer ToDo's

### ISSUE THREAD

**Issue by jogibear9988** [icsharpcode/WpfDesigner#18]
- [ ] Rework Rotating/Skewing (maybe use Code from https://github.com/jogibear9988/transformbox (MIT))
- [ ] Drag Controls to Transparent Containers
- [ ] DesignTime Collection Editor should support NewItemTypes Attribute (maybe we need to support DesignTimeDlls)
- [ ] StaticResourceExtension should use IAmbientProvider instead of a Wrapper.
- [ ] Snapline support for SameDistance as another Object has
- [ ] Change "ValueOnInstance" so that changes in DesignWidth do not change "Width" in property Grid
- [ ] Paste should use actual Position as upper offset (so the inserted Elements are not out of Screen)
- [ ] Snap Line/Path/Polyline Edit in 15° (like Blend)
- [x] Check that Line/Path/Poline Edit also works in Grid, not only Canvas
- [ ] Snapline and Rasterplacement should be used while Editing Lines/Path/Polyline (skip with Ctrl)
- [ ] Better way to Add Points to Line/Path/Polyline
- [ ] Support of Line/Path/Polyline Edit when zoomed
- [ ] Rework Keyboard modifiers (should be same Blend uses)

**Comment by javidang** [comment]
Hi. Adding binding support (setting binding from property grid) is viable ? I tried to add in xaml something like "ItemSource={Binding List}" , but form disappears when i switch to design mode.

**Comment by jogibear9988** [comment]
Please create a new Issue if you have a Bug! This is only a List of Todo's for myself! 

Don't know what you mean what does not work! If I have XAML like this

     <Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Width="640"
        Height="480">
  <Canvas>
    <ListBox Width="120"
             Height="100"
             ItemsSource="{Binding List}"
             Canvas.Left="179"
             Canvas.Top="153" />
  </Canvas>
     </Window>

I can switch to Design View
