### ISSUE TITLE
Bugs, ToDo's :

### ISSUE THREAD

**Issue by jogibear9988** [icsharpcode/WpfDesigner#3]
Todo's in the WPF Designer

- [ ] Changing size of a Rotated/Skewed Control not working corretly (maybe use code from https://transformbox.codeplex.com/ is under MIT Licence)
- [ ] Rotateing Extension buggy
- [ ] Controls could not be draged into Transparent Control
- [ ] Design Time Collection Editor should support newItemTypes Attribute (for this we maybe need also support of Design Time DLLs)
- [x] ~~Support for Line, Path, ... maybe use Code from XDraw (https://xdraw.codeplex.com), it's also MIT Licenced~~
- [ ] StaticResourceExtension should use IAmbientProvider instead of a Wrapper.
- [x] Bindings should be changed when they copied, and the Bound Element is also copied
- [x] Image Control with no Image and no Size Set does not work correctly in Canvas and Grid!
- [x] ~~Support for DesignHeight/Width~~
- [x] AvalonDock2 Child Elements are not Displayed in the Outline View, why? It's working in VS!
- [x] ~~Sometimes Copy&Paste adds Extra Namespaces wich already exist in the XAML file~~

**Comment by jogibear9988** [comment]
Maybe we need to change something in "ValueOnInstance" of XamlProperty, so after set of DesignWith or Height, that the Value of Width is backed up, so the Display in Property Grid is correct! But atm. this is a small ignorable issue...

**Comment by jogibear9988** [comment]
Snaplines enhanchment:

- Middle betwee two objects.
- Same Distance as another Object:
